batch_size: 4
clip_range: 0.2
ent_coef: 0.01
gamma: 0.99
learning_rate: 0.00025
max_grad_norm: 0.5
n_epochs: 4
n_steps: 128
policy_kwargs:
  net_arch:
  - pi:
    - 100
    - 100
  - vf:
    - 100
    - 100
seed: 123
tensorboard_log: PPO_092722_004113/seed-123/logs
verbose: 2
