batch_size: 64
learning_rate: 0.00025
n_steps: 512
policy_kwargs:
  net_arch:
  - pi:
    - 100
    - 100
  - vf:
    - 100
    - 100
sde_sample_freq: 100
seed: 123
tensorboard_log: TRPO_092922_190923/seed-123/logs
use_sde: true
verbose: 2
